# Site Settings
title: BTA's Blog | Blogger & Web Development
email: contact@buitruonganh.com
description: Capture and save the best solutions for WEB Development.
baseurl: "/btablog" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: buitruonganh
user_description: Web developer.
disqus_username: buitruonganh

# Social Media
# Remove the item if you don't need it
github_username: buitruonganh
facebook_username: buitruonganh
twitter_username: buitruonganh
instagram_username: bui.truonganh
linkedin_username: buitruonganh
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
